name: 'adinsight'
version: '1.0.0'
config-version: 2

profile: 'adinsight360'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target"]

require-dbt-version: [">=1.9.4", "<2.0.0"]
