version: 2

models:
  - name: stg_reddit_posts
    description: Staged Reddit marketing posts
    columns:
      - name: id
        description: Unique identifier for the post
        tests:
          - unique
          - not_null
      - name: title
        description: Post title
        tests:
          - not_null
      - name: score
        description: Post score (upvotes - downvotes)
      - name: created_utc
        description: Post creation timestamp in UTC
        tests:
          - not_null
      - name: url
        description: Post URL
      - name: num_comments
        description: Number of comments on the post
      - name: author
        description: Username of the post author
      - name: loaded_at
        description: Timestamp when the record was loaded
        tests:
          - not_null 